# Generated by Django 5.1.7 on 2025-03-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostpital_name', models.CharField(max_length=255)),
                ('location_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.location')),
            ],
        ),
    ]
