# Generated by Django 5.1.7 on 2025-03-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.location'),
        ),
    ]
