# Generated by Django 5.1.7 on 2025-03-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_hospital_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
