# Generated by Django 5.1.2 on 2025-03-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_location_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(blank=True, max_length=100, null=True)),
                ('report_file', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.hospital')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.location')),
            ],
        ),
    ]
