# Generated by Django 5.1.2 on 2025-03-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_reports_location_alter_reports_hospital'),
        ('hospital_authorities', '0003_alter_hospitalauthority_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.location'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_authorities.hospitalauthority'),
        ),
    ]
