# Generated by Django 5.1.2 on 2025-04-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_reports_location_alter_reports_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
