# Generated by Django 5.1.2 on 2025-04-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_reports_report_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='report_public_id',
        ),
    ]
