# Generated by Django 5.1.7 on 2025-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_uploadedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedreport',
            name='file',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
