# Generated by Django 5.1.7 on 2025-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingexecutive',
            name='due',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketingexecutive',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
