# Generated by Django 5.1.7 on 2025-03-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_hospital_location_name'),
        ('marketing_executives', '0002_alter_marketingexecutive_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingexecutive',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.location'),
        ),
    ]
