# Generated by Django 5.1.7 on 2025-03-12 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executives', '0003_alter_marketingexecutive_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite_amount', models.IntegerField()),
                ('deposite_document', models.URLField(max_length=255)),
                ('deposite_date', models.DateField()),
                ('deposite_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
