# Generated by Django 5.1.7 on 2025-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executives', '0004_deposites'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingexecutive',
            name='extra_paid',
            field=models.IntegerField(default=0),
        ),
    ]
