# Generated by Django 5.1.7 on 2025-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executives', '0005_marketingexecutive_extra_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category', models.CharField(choices=[('BIOCHEMICAL TEST', 'BIOCHEMICAL TEST'), ('REPRODUCTIVE HORMONE', 'REPRODUCTIVE HORMONE'), ('URINE ANALYSIS', 'URINE ANALYSIS'), ('KIDNEY FUNCTION TEST (KFT)', 'KIDNEY FUNCTION TEST (KFT)'), ('SPECIAL BIOCHEMICAL TEST', 'SPECIAL BIOCHEMICAL TEST'), ('METABOLIC HORMONE', 'METABOLIC HORMONE'), ('CANCER MARKER', 'CANCER MARKER'), ('LIVER FUNCTION TEST (LFT)', 'LIVER FUNCTION TEST (LFT)')], default='BIOCHEMICAL TEST', max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.CharField(max_length=255)),
                ('patient_rate', models.IntegerField()),
                ('test_sample', models.CharField(choices=[('Serum', 'Serum'), ('Pus', 'Pus'), ('Blood (EDTA Tube)', 'Blood (EDTA Tube)'), ('Blood (PT Tube)', 'Blood (PT Tube)'), ('Blood (RBS Tube)', 'Blood (RBS Tube)'), ('Blood (Red Tube)', 'Blood (Red Tube)'), ('Body Fluid', 'Body Fluid'), ('Urine', 'Urine')], default='Serum', max_length=20)),
                ('test_reporting', models.CharField(choices=[('One Day', 'One Day'), ('Two Days', 'Two Days'), ('Three Days', 'Three Days'), ('Four Days', 'Four Days'), ('Five Days', 'Five Days'), ('Seven Days', 'Seven Days'), ('Ten Days', 'Ten Days')], default='One Day', max_length=20)),
                ('tg_rate', models.IntegerField()),
                ('tg2_rate', models.IntegerField()),
                ('tg3_rate', models.IntegerField()),
                ('tg4_rate', models.IntegerField()),
                ('tg5_rate', models.IntegerField()),
                ('sd_rate', models.IntegerField()),
                ('sd2_rate', models.IntegerField()),
                ('nr_rate', models.IntegerField()),
                ('nrm_rate', models.IntegerField()),
                ('nr2_rate', models.IntegerField()),
                ('feni_rate', models.IntegerField()),
                ('mkg_rate', models.IntegerField()),
                ('ks_rate', models.IntegerField()),
            ],
        ),
    ]
