# Generated by Django 5.1.2 on 2025-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executives', '0006_labservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labservices',
            name='feni_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='ks_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='mkg_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='nr2_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='nr_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='nrm_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='sd2_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='sd_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='tg2_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='tg3_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='tg4_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='tg5_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labservices',
            name='tg_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
