# Generated by Django 5.1.7 on 2025-10-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='report_id',
        ),
    ]
