# Generated by Django 5.1.7 on 2025-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_report', '0002_alter_doctorreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreport',
            name='report_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctorreport',
            unique_together={('doctor', 'report_id')},
        ),
    ]
