# Generated by Django 5.1.7 on 2025-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_report', '0003_doctorreport_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreport',
            name='patient_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='specimen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
