# Generated by Django 5.1.7 on 2025-10-01 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_report', '0004_doctorreport_patient_age_doctorreport_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreport',
            name='receive_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Actual sample receive date'),
        ),
    ]
