# Generated by Django 5.1.7 on 2025-10-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_report', '0005_doctorreport_receive_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True, help_text='Date of payment entry')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='payment_docs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='doctor_report.doctorprofile')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='doctor_report.doctorprofile')),
                ('reports', models.ManyToManyField(related_name='payments', to='doctor_report.doctorreport')),
            ],
        ),
    ]
