# Generated by Django 5.1.2 on 2025-03-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_location_is_selected'),
        ('hospital_authorities', '0002_alter_hospitalauthority_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalauthority',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.location'),
        ),
    ]
